#!/usr/bin/env python3
"""
fix_symlinks.py -- make the shared safety files survive a transfer.

THE PROBLEM
-----------
`cf_core.py` and `cf_keyboard.py` exist in two places: the stack root and
inside the ROS package.  They were symlinks.  Symlinks do not survive most
transfers.  The copy to pear-2 dropped them entirely and the test suite died
on ImportError -- that was the LOUD failure.  The quiet one is a transfer that
DEREFERENCES them, leaving two real files that then drift apart, so the ROS
node and the teleop enforce different safety limits and nothing complains.

THE FIX
-------
Real files everywhere, one nominated canonical copy, and a test that fails the
moment they differ.  Drift becomes a red test instead of a silent divergence.

    python3 fix_symlinks.py            # report only, changes nothing
    python3 fix_symlinks.py --apply    # convert links, write manifest + test
    python3 fix_symlinks.py --sync     # after editing a canonical, push it out

Run from inside cf_vicon_stack.
"""
import argparse
import hashlib
import json
import os
import shutil
import sys

MANIFEST = "DUPLICATES.json"
TESTFILE = "test_duplicates.py"
SKIP_DIRS = {".git", "build", "install", "log", "__pycache__", ".cache", "cache"}
# Directories that legitimately hold OLD copies of tracked files. They must
# never be treated as duplicates-that-must-match: they are rollback snapshots,
# so they are SUPPOSED to differ, and syncing onto them would destroy the only
# way back from a bad patch.
SKIP_PREFIXES = ("_backup", "_to_delete", "_old", ".venv", "venv")


def _skip(name):
    return name in SKIP_DIRS or name.startswith(SKIP_PREFIXES)


def walk(root):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not _skip(d)]
        for f in filenames:
            yield os.path.join(dirpath, f)


def rel(root, p):
    return os.path.relpath(p, root).replace(os.sep, "/")


def sha(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def discover(root):
    """Group files that must stay identical: symlinks, plus same-name twins."""
    links, by_name = [], {}
    for p in walk(root):
        if os.path.islink(p):
            links.append(p)
        by_name.setdefault(os.path.basename(p), []).append(p)

    groups = {}
    for p in links:
        tgt = os.path.realpath(p)
        if not os.path.exists(tgt):
            groups.setdefault("DANGLING:" + rel(root, p), [])
            continue
        groups.setdefault(rel(root, tgt), []).append(rel(root, p))

    # same-named .py twins that are not already linked (the dereferenced case)
    for name, paths in by_name.items():
        if not name.endswith(".py") or len(paths) < 2:
            continue
        if name in (os.path.basename(TESTFILE),):
            continue
        rels = sorted(rel(root, p) for p in paths)
        canon = min(rels, key=lambda r: (r.count("/"), len(r)))
        rest = [r for r in rels if r != canon]
        if canon in groups:
            for r in rest:
                if r not in groups[canon]:
                    groups[canon].append(r)
        elif not any(canon in v or any(r in v for r in rest) for v in groups.values()):
            groups[canon] = rest
    return groups


TEST_SRC = '''"""AUTO-GENERATED by fix_symlinks.py -- do not edit by hand.

Guards the shared safety files. If this fails, the teleop and the ROS node are
enforcing DIFFERENT limits and one of them is wrong.
Fix: edit the canonical file, then run  python3 fix_symlinks.py --sync
"""
import hashlib
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
SKIP = {".git", "build", "install", "log", "__pycache__", ".cache", "cache"}
SKIP_PREFIXES = ("_backup", "_to_delete", "_old", ".venv", "venv")


def _skip(name):
    return name in SKIP or name.startswith(SKIP_PREFIXES)


def _sha(p):
    with open(p, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def _manifest():
    with open(os.path.join(ROOT, "DUPLICATES.json")) as fh:
        return json.load(fh)["groups"]


def test_no_symlinks_anywhere():
    bad = []
    for dp, dn, fn in os.walk(ROOT):
        dn[:] = [d for d in dn if not _skip(d)]
        bad += [os.path.relpath(os.path.join(dp, f), ROOT)
                for f in fn if os.path.islink(os.path.join(dp, f))]
    assert not bad, ("symlinks will not survive transfer to the lab PC: %s\\n"
                     "run: python3 fix_symlinks.py --apply" % bad)


def test_copies_present_and_identical():
    problems = []
    for g in _manifest():
        canon = os.path.join(ROOT, g["canonical"])
        if not os.path.exists(canon):
            problems.append("MISSING canonical %s" % g["canonical"])
            continue
        want = _sha(canon)
        for c in g["copies"]:
            p = os.path.join(ROOT, c)
            if not os.path.exists(p):
                problems.append("MISSING %s (transfer dropped it)" % c)
            elif _sha(p) != want:
                problems.append("DRIFTED %s != %s" % (c, g["canonical"]))
    assert not problems, ("shared safety files diverged:\\n  %s\\n"
                          "run: python3 fix_symlinks.py --sync"
                          % "\\n  ".join(problems))
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--sync", action="store_true")
    a = ap.parse_args()
    root = os.path.abspath(a.root)

    mpath = os.path.join(root, MANIFEST)

    if a.sync:
        if not os.path.exists(mpath):
            sys.exit("no %s -- run --apply first." % MANIFEST)
        groups = json.load(open(mpath))["groups"]
        n = 0
        for g in groups:
            canon = os.path.join(root, g["canonical"])
            if not os.path.exists(canon):
                sys.exit("canonical missing: %s" % g["canonical"])
            for c in g["copies"]:
                p = os.path.join(root, c)
                # A symlink reads byte-identical to its target, so the hash
                # check alone would leave it in place. It must go regardless.
                link = os.path.islink(p)
                if link:
                    os.unlink(p)
                elif os.path.exists(p) and sha(p) == sha(canon):
                    continue
                os.makedirs(os.path.dirname(p), exist_ok=True)
                shutil.copy2(canon, p)
                print("  synced  %s  <- %s%s"
                      % (c, g["canonical"], "  (was a symlink)" if link else ""))
                n += 1
        print("\n  %d file(s) synced." % n if n else "\n  already in sync.")
        return

    groups = discover(root)
    dangling = [k for k in groups if k.startswith("DANGLING:")]
    real = {k: v for k, v in groups.items() if not k.startswith("DANGLING:") and v}

    print("\n  root: %s" % root)
    if dangling:
        print("\n  BROKEN SYMLINKS (target gone -- this is the pear-2 failure):")
        for d in dangling:
            print("    %s" % d[9:])
        print("  Cannot repair automatically: restore the file from the laptop first.")
    if not real:
        print("\n  no duplicate groups found.")
        if not dangling:
            print("  Nothing to do.")
        return

    print("\n  shared files that must stay identical:")
    for canon, copies in sorted(real.items()):
        cp = os.path.join(root, canon)
        h = sha(cp)[:12] if os.path.exists(cp) else "MISSING"
        print("    %s   [%s]" % (canon, h))
        for c in copies:
            p = os.path.join(root, c)
            if not os.path.exists(p):
                state = "MISSING"
            elif os.path.islink(p):
                state = "symlink -> will become a real file"
            elif sha(p) == sha(cp):
                state = "identical"
            else:
                state = "*** DRIFTED ***"
            print("      %-58s %s" % (c, state))

    if not a.apply:
        print("\n  report only. re-run with --apply to fix.")
        return

    changed = 0
    for canon, copies in real.items():
        cp = os.path.join(root, canon)
        if not os.path.exists(cp):
            sys.exit("canonical missing: %s" % canon)
        for c in copies:
            p = os.path.join(root, c)
            if os.path.islink(p):
                os.unlink(p)
            elif os.path.exists(p) and sha(p) == sha(cp):
                continue
            os.makedirs(os.path.dirname(p), exist_ok=True)
            shutil.copy2(cp, p)
            print("  wrote real file  %s" % c)
            changed += 1

    with open(mpath, "w") as fh:
        json.dump({"_comment": "generated by fix_symlinks.py; guarded by "
                               + TESTFILE,
                   "groups": [{"canonical": k, "copies": sorted(v)}
                              for k, v in sorted(real.items())]}, fh, indent=2)
        fh.write("\n")
    with open(os.path.join(root, TESTFILE), "w") as fh:
        fh.write(TEST_SRC)
    print("\n  wrote %s and %s" % (MANIFEST, TESTFILE))
    print("  %d file(s) converted. Now run:  python3 -m pytest %s -q" % (changed, TESTFILE))


if __name__ == "__main__":
    main()
