"""AUTO-GENERATED by fix_symlinks.py -- do not edit by hand.

Guards the shared safety files. If this fails, the teleop and the ROS node are
enforcing DIFFERENT limits and one of them is wrong.
Fix: edit the canonical file, then run  python3 fix_symlinks.py --sync
"""
import hashlib
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
SKIP = {".git", "build", "install", "log", "__pycache__", ".cache", "cache"}
SKIP_PREFIXES = ("_backup", "_to_delete", "_old", ".venv", "venv")


def _skip(name):
    return name in SKIP or name.startswith(SKIP_PREFIXES)


def _sha(p):
    with open(p, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def _manifest():
    with open(os.path.join(ROOT, "DUPLICATES.json")) as fh:
        return json.load(fh)["groups"]


def test_no_symlinks_anywhere():
    bad = []
    for dp, dn, fn in os.walk(ROOT):
        dn[:] = [d for d in dn if not _skip(d)]
        bad += [os.path.relpath(os.path.join(dp, f), ROOT)
                for f in fn if os.path.islink(os.path.join(dp, f))]
    assert not bad, ("symlinks will not survive transfer to the lab PC: %s\n"
                     "run: python3 fix_symlinks.py --apply" % bad)


def test_copies_present_and_identical():
    problems = []
    for g in _manifest():
        canon = os.path.join(ROOT, g["canonical"])
        if not os.path.exists(canon):
            problems.append("MISSING canonical %s" % g["canonical"])
            continue
        want = _sha(canon)
        for c in g["copies"]:
            p = os.path.join(ROOT, c)
            if not os.path.exists(p):
                problems.append("MISSING %s (transfer dropped it)" % c)
            elif _sha(p) != want:
                problems.append("DRIFTED %s != %s" % (c, g["canonical"]))
    assert not problems, ("shared safety files diverged:\n  %s\n"
                          "run: python3 fix_symlinks.py --sync"
                          % "\n  ".join(problems))
