#!/usr/bin/env bash
# Run ONCE on the Linux host that has the Crazyradio plugged in.
#
#   ./host-setup.sh          <- correct
#   sudo ./host-setup.sh     <- also works now, but it did NOT before: see below
#
# Installs udev rules, puts you in plugdev and docker, and writes the build
# args to docker/.env so `docker compose` picks them up with no exports.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Who is "you"?
#
# Under sudo, $USER / id -u / id -g all report ROOT. The first version of this
# script used those directly, so running it the obvious way -- with sudo,
# because it installs udev rules -- silently produced USER_UID=0 USER_GID=0 and
# added *root* to plugdev. Build with those args and the container runs as UID
# 0, so every file it writes into the workspace comes out root-owned on the
# host. Resolve the invoking user instead.
# ---------------------------------------------------------------------------
REAL_USER="${SUDO_USER:-${USER:-$(id -un)}}"
if [ "${REAL_USER}" = "root" ]; then
    echo "Refusing to continue: cannot tell which non-root user to set up." >&2
    echo "Log in as your normal user and run:  ./host-setup.sh" >&2
    exit 1
fi
REAL_UID="$(id -u "${REAL_USER}")"
REAL_GID="$(id -g "${REAL_USER}")"
echo "== 0. target user =="
echo "   ${REAL_USER}  (uid ${REAL_UID}, gid ${REAL_GID})"

echo "== 1. udev rules =="
sudo cp "${HERE}/99-bitcraze.rules" /etc/udev/rules.d/99-bitcraze.rules
sudo udevadm control --reload-rules
sudo udevadm trigger
echo "   installed /etc/udev/rules.d/99-bitcraze.rules"

echo "== 2. groups =="
NEED_RELOGIN=0
for g in plugdev docker; do
    getent group "$g" >/dev/null || sudo groupadd "$g"
    if id -nG "${REAL_USER}" | tr ' ' '\n' | grep -qx "$g"; then
        echo "   ${REAL_USER} is already in ${g}"
    else
        sudo usermod -aG "$g" "${REAL_USER}"
        echo "   added ${REAL_USER} to ${g}"
        NEED_RELOGIN=1
    fi
done

echo "== 3. what is actually plugged in =="
if command -v lsusb >/dev/null; then
    lsusb | grep -i -E '1915|bitcraze|0483:5740' || {
        echo "   no Bitcraze device found by lsusb."
        echo "   Plug the Crazyradio in and re-run. If it shows an id other than"
        echo "   1915:7777, add a rule for it to 99-bitcraze.rules -- and note that"
        echo "   cflib only looks for 0x7777, so the dongle may need the"
        echo "   CRPA-emulation firmware."; }
else
    echo "   lsusb not installed (apt install usbutils)"
fi

echo
echo "== 4. build args for this machine =="
PLUGDEV_GID="$(getent group plugdev | cut -d: -f3)"
ENVFILE="${HERE}/.env"
cat > "${ENVFILE}" <<ARGS
# Generated by host-setup.sh on $(date -Iseconds) for ${REAL_USER}@$(hostname).
# Machine-specific: do NOT copy this file to another machine or commit it.
# docker compose reads it automatically from this directory.
USER_UID=${REAL_UID}
USER_GID=${REAL_GID}
PLUGDEV_GID=${PLUGDEV_GID}
ARGS
sudo chown "${REAL_UID}:${REAL_GID}" "${ENVFILE}"
sed 's/^/   /' "${ENVFILE}"
echo
echo "   wrote ${ENVFILE} -- no exports needed, compose reads it from here."

if [ "${NEED_RELOGIN}" = "1" ]; then
    echo
    echo "== group membership changed =="
    echo "   Log out and back in, or for this shell only:"
    echo "     sg docker -c 'docker compose build'"
fi
